spring.application.name=roottrace
server.port=8081

roottrace.enable =true

spring.datasource.url=jdbc:postgresql://localhost:5432/roottrace
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true