spring.application.name=roottrace
server.port=8081

spring.datasource.url=YOUR_DATABASE_URL
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD

openai.api.key=YOUR_OPENAI_API_KEY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

